name: merged

on:
  pull_request:
    paths:
      - ".github/workflows/merged.yaml"
jobs:
  apply:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.base_ref == 'master'
    steps:
      - run: echo ${{ github.base_ref }}    