name: merged

on:
  pull_request:
    paths:
      - ".github/workflows/merged.yaml"
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - run: echo test
  apply:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.base_ref }}    