name: terraform

on:
  pull_request:
    paths:
      - ".github/workflows/test.yaml"
  issue_comment:
    types: [created]

jobs:
  prepare:
    if: | 
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/plan'))
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          BODY="${{ github.event.comment.body }}"
          ./test.sh ${BODY#/test }
  