name: terraform

on:
  pull_request:
    paths:
      - ".github/workflows/test.yaml"
  issue_comment:
    types: [created]

jobs:
  prepare:
    if: | 
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/test'))
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: 
          BODY=${{ github.event.comment.body }}
          ./test.sh ${BODY#/test }
        
  test:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ matrix.env }}
  